# Generated by Django 3.1 on 2020-08-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_address_conversation_listing_listingphoto_message_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='not available', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='headline',
            field=models.CharField(default='not available', max_length=255),
            preserve_default=False,
        ),
    ]
