# Generated by Django 3.1 on 2020-08-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200816_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingphoto',
            name='filepath',
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(default='notavail.png', upload_to='../../src/assetts'),
            preserve_default=False,
        ),
    ]
