# Generated by Django 3.1 on 2020-08-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200826_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='listings',
            field=models.ManyToManyField(related_name='amentities', related_query_name='amenity', to='main.Listing'),
        ),
    ]
