# Generated by Django 3.1 on 2020-08-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200826_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
