# Generated by Django 3.1 on 2020-09-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200905_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
